### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by keugene-git** [keugene-git/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by heeven** [comment]
Life timeline (ofc events took place in a parallel world lul)
1991 - kicked the Ivo Robotnik's ass
1992 - kicked the Ivo Robotnik's ass again, but with my comrade Tails (Miles Prower)
1993 - recaptured my future girlfriend from the Metal Sonic and kicked the Ivo Robotnik's ass... again
1994 - beat up Knuckles the Echidna and disrupted the launch of Death Egg
1994 - destroyed the Death Egg and saved Knuckles (now my best pal)
1998 - wiped out Chaos (nothing can't stop me, even the powerful ancient creature KEKW)
2001 - helped Shadow to defeat his "brother" Biolizard
2003 - beat up Metal Overlord with my gangsta party
2006 - saved princess Elise ( ͡° ͜ʖ ͡°)
2008 - took part in the restoration of the planet destroyed by the monster Dark Gaia
2010 - saved little wisps (little cuties (｡◕‿‿◕｡) )
2010 - made the lives of Badniks look like hell (RIP AND SHRED THEM ALL!!1)
2011 - met... myself... WHAT!?
2012 - kicked the Metal Sonic's and Ivo Robotnik's asses
2013 - defeated Deadly Six
2016 - kicked the Ivo Robotnik's ass.. it already sounds like a joke, heh
2016 - captured by Robotnik aka EGGHEAD lul

Achievements
1993 -  had a personal balloon in Macy's Thanksgiving Day Parade
1993 - symbol of the Williams Grand Prix team on the 1993 Formula One championship
1993-1997 - symbol of the JEF United Ichihara Chiba football team
1996 -  first video game character to be seen in a Rose Parade
2004 - won a Golden Joystick Award for "The Sun Ultimate Gaming Hero"
2005 - inducted on the inaugural Walk of Game class
2011 - ranked as the 14th greatest video game character by Empire
2011 - was voted 10th out of the top 50 video game characters of all time in Guinness World Records 2011 Gamers' Edition

Acting
1993 - Adventures of Sonic the Hedgehog
1993 - Sonic the Hedgehog
1996 - Sonic the Hedgehog: The Movie
1999 - Sonic Underground
2003-2009 - Sonic X
2014-2017 - Sonic Boom
2020 - Sonic the Hedgehog (film)
