### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by keugene-git** [keugene-git/homepage#7]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by heeven** [comment]
https://www.sonicthehedgehog.com/
https://www.facebook.com/Sonic/
https://www.twitter.com/sonic_hedgehog
https://www.youtube.com/user/sonic
https://www.instagram.com/sonicthehedgehog/
