### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by keugene-git** [keugene-git/homepage#8]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by heeven** [comment]
I , Sonic the Hedgehog, am present to announce that I am obligated, by my own preference to exceed the Normal speed that I would normally "go", and after the end this speech I will start moving my limbs in a way which will most likely give me permanent damage as I am a hedgehog and should not be this accelerated.
